version: 0.2

phases:
  install:
    commands:    
      - mvn install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 562032292525.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...          
      - docker build -t java-app-jcdiamante .
      - docker tag java-app-jcdiamante:latest 562032292525.dkr.ecr.ap-southeast-1.amazonaws.com/java-app-jcdiamante:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 562032292525.dkr.ecr.ap-southeast-1.amazonaws.com/java-app-jcdiamante:latest
